services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/usr/wpp-server/dist/config.js
      - ./tokens:/usr/wpp-server/tokens
    ports:
      - '21465:21465'
