services:
  server:
    container_name: server
    restart: unless-stopped
    pull_policy: build
    build:
      context: .
    image: wppconnect-server
    volumes:
      - ./config.ts:/usr/wpp-server/src/config.ts
      - ./tokens:/usr/wpp-server/tokens
      - ./usersData:/usr/wpp-server/usersData
      - data:/usr/wpp-server
    ports:
      - '21465:21465'
    networks:
      - wpp-network
    tty: true
volumes:
  data: {}
networks:
  wpp-network:
    name: wpp-network
    driver: bridge
