services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./src/config.ts:/usr/wpp-server/src/config.ts
      - ./tokens:/usr/wpp-server/tokens
    ports:
      - '21465:21465'
