version: "3"

services:
  wppconnect:
    build:
      context: .
    volumes:
      - ./src/config.ts:/usr/src/wpp-server/config.ts
      - ./tokens:/usr/src/wpp-server/tokens
    ports:
      - "21465:21465"

volumes:
  wppconnect_tokens: {}